# Generated by Django 4.1.1 on 2024-11-01 02:12

from django.db import migrations, models

def create_sample_profiles(apps, schema_editor):
    Profile = apps.get_model('base', 'Profile')
    Profile.objects.values('name', 'bio', 'degree', 'course').distinct()
    Profile.objects.create(name="Bob", bio="Avid gamer.", course="Software Engineering", degree="Computer Science", gender="Male")
    Profile.objects.create(name="Alice", bio="Loves hiking.", course="Biochemistry", degree="Biology", gender="Female")
    Profile.objects.values('name', 'bio', 'degree', 'course').distinct()
    
class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
