# Generated by Django 4.1.1 on 2024-11-02 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_interests_profile_major_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cleanliness',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, help_text='How clean do you keep your space? (1-10)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness_importance',
            field=models.IntegerField(default=5, help_text='How important is cleanliness matching? (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='guests_importance',
            field=models.IntegerField(default=5, help_text='How important is guest preference matching? (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='guests_preference',
            field=models.CharField(choices=[('Rarely', 'Rarely/Never'), ('Sometimes', 'Sometimes'), ('Often', 'Often')], default='Sometimes', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_importance',
            field=models.IntegerField(default=5, help_text='How important is noise level matching? (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_level',
            field=models.CharField(choices=[('Quiet', 'Prefer Quiet'), ('Moderate', 'Moderate Noise OK'), ('Active', 'Active/Social Environment')], default='Moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_schedule',
            field=models.CharField(choices=[('Early_Bird', 'Early Bird (Before 10 PM)'), ('Night_Owl', 'Night Owl (After 10 PM)'), ('Flexible', 'Flexible')], default='Flexible', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_schedule_importance',
            field=models.IntegerField(default=5, help_text='How important is sleep schedule matching? (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
