# Generated by Django 4.1.1 on 2024-11-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_profile_email_confirmed_and_more'),
    ]

    operations = [
    ]
